name: h5cloud
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib-base
  - pandas
  - numpy
  - s3fs
  - xarray
  - fsspec
  - dask
  - distributed
  - geopandas
  - h5py>3.9
  - zarr
  - kerchunk
  - h5netcdf
  - pip
  - pip:
    - h5coro
